server:
  port: 9001

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer
          uri: http://localhost:90
          predicates:
            - Path=/consumer/**
        - id: article
          uri: http://localhost:9010
          predicates:
            - Path=/article/**


